sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: UvQ4ZUhNG8acrXlGbsIBhTq0UWx/BC0TuFbFiivpJUrqvNqysmga7wG5gZinFA2HZVK13qDHG/9nMIuHuX6DL7YSUQ4/WQ/xbrHgoc9694txo7PHMhBc5URzvjRb+vVVA/7MuGBysCgASi/YkJfZd7y+pZmiAtaSt9nCW16OeOK4IfhY+DlTtVHFaEcoRzNklat0I0r88VHrxVFpiRe443kZwITtAQ0KFmpmad7b/7XGJrChuf5gYGF/hPCrNEiT46SSvZiSLjcw1vEl8d2/23qnVt5vc3277GQesglgSzt7npqOfWZ7GtytxwytolAhAVVGERM3GiJDnAkgNGOmyX6Z+hrDxfL1moCEU/hLu8grusIptTKE9SmPfdhmobxCf4oqe3MwJ7jEgyaZCAqiI+Na85NhiL2yvGEQ8Bk6ZtKAS7dsLNPiLP0btYJHbzzNildoeqcfzdkitx+1DLykUL+zUUoTQVnvjTF2iynPhqb0l2wki4MZ8BawtNRwpoBfZjjGAscHUW/D/fpOH/gK2IMvU+iq6Rd192KsbjTG2wLE3cMfJZEDUJyzquuU1Wut5GPpcU7Nw7MLbvDali62Ln1U97TSDTPFrU9mdrxmMMLxip9mai4a83FTkdvMPpvYDgdcE9bZCWPXPtB6qSNZCXStCjzIHnHM+JV++0dtI54=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: OMsQu4upu4aPqi/WUfsCgmNzXTMR1f8OLaWvmMJpRyZ4u2JHtL+jgPu8CQjIMQl47ufz8k8XNcS6Lsbs/T9SfBQRe2zArtsq3xTwKAC9UgimFttpJf6Jf3SdGLgFg/osykQqeSRjLGexiOAYy1my+bjjg3VyinlOZXd/Ek8qHXX+f1OzflnuopKfoD9fYY7mIhRJWXIQCdSQWlMCxoGFySChOAGTudN40MgRfeLjnkQGNrWoi8uS15ZAYr4OJXTb3ggYmViUs2Kz3EtV4ng2RCOmUadl2fnWjpYRlWT4aFG9mbH51VV9tkt0kJeSQeQIODIWEVpemTE3hvpTZ8t3+lpBmlMc2qafYHgoov2MEWtcuRLVWemTQ3huDtoN6Y8XHUyh9ywG451rRdLtMNiWkxSbSbimKlcFmR+v8uG2Wjq530OKFW3LO37jmK+4bz+NS10/OjWS14S67MS2U5ilOXzGEXSyG2eJjwCBuCzCH8DCAyZ3mEoiyc+tuXSFZ/H7zvbccVGZvLsoReSUYMH6oz2LpW2LJncXngCNuEM+wl2hCXtTAvBAt8jQxMAIa2/5pDbtfdYoZTmSR1H6S5INWw3WGdKC8uW7/qgLcuP+585dBao/NrNDKSAJ3uEGH3TUtwXqHhscDqqGSvpS0HznABMvDyXrLSheOzKlIpKpYmY=
