sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: OMsQu4upu4aPqi/WUfsCgmNzXTMR1f8OLaWvmMJpRyZ4u2JHtL+jgPu8CQjIMQl47ufz8k8XNcS6Lsbs/T9SfBQRe2zArtsq3xTwKAC9UgimFttpJf6Jf3SdGLgFg/osykQqeSRjLGexiOAYy1my+bjjg3VyinlOZXd/Ek8qHXX+f1OzflnuopKfoD9fYY7mIhRJWXIQCdSQWlMCxoGFySChOAGTudN40MgRfeLjnkQGNrWoi8uS15ZAYr4OJXTb3ggYmViUs2Kz3EtV4ng2RCOmUadl2fnWjpYRlWT4aFG9mbH51VV9tkt0kJeSQeQIODIWEVpemTE3hvpTZ8t3+lpBmlMc2qafYHgoov2MEWtcuRLVWemTQ3huDtoN6Y8XHUyh9ywG451rRdLtMNiWkxSbSbimKlcFmR+v8uG2Wjq530OKFW3LO37jmK+4bz+NS10/OjWS14S67MS2U5ilOXzGEXSyG2eJjwCBuCzCH8DCAyZ3mEoiyc+tuXSFZ/H7zvbccVGZvLsoReSUYMH6oz2LpW2LJncXngCNuEM+wl2hCXtTAvBAt8jQxMAIa2/5pDbtfdYoZTmSR1H6S5INWw3WGdKC8uW7/qgLcuP+585dBao/NrNDKSAJ3uEGH3TUtwXqHhscDqqGSvpS0HznABMvDyXrLSheOzKlIpKpYmY=
